import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f3fcf0',
        'surface-dim': '#d4ddd1',
        'surface-bright': '#f3fcf0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#edf6ea',
        'surface-container': '#e7f0e5',
        'surface-container-high': '#e2ebdf',
        'surface-container-highest': '#dce5d9',
        'on-surface': '#161d16',
        'on-surface-variant': '#45474d',
        'inverse-surface': '#2a322b',
        'inverse-on-surface': '#eaf3e7',
        outline: '#75777d',
        'outline-variant': '#c5c6cd',
        'surface-tint': '#545e76',
        primary: '#051125',
        'on-primary': '#ffffff',
        'primary-container': '#1b263b',
        'on-primary-container': '#828da7',
        'inverse-primary': '#bbc6e2',
        secondary: '#b7102a',
        'on-secondary': '#ffffff',
        'secondary-container': '#db313f',
        'on-secondary-container': '#fffbff',
        tertiary: '#001415',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#002b2d',
        'on-tertiary-container': '#659597',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#bbc6e2',
        'on-primary-fixed': '#101b30',
        'on-primary-fixed-variant': '#3c475d',
        'secondary-fixed': '#ffdad8',
        'secondary-fixed-dim': '#ffb3b1',
        'on-secondary-fixed': '#410007',
        'on-secondary-fixed-variant': '#92001c',
        'tertiary-fixed': '#b9ecee',
        'tertiary-fixed-dim': '#9ecfd1',
        'on-tertiary-fixed': '#002021',
        'on-tertiary-fixed-variant': '#1a4e50',
        background: '#f3fcf0',
        'on-background': '#161d16',
      },
      fontFamily: {
        manrope: ['var(--font-manrope)', 'sans-serif'],
        space: ['var(--font-space-mono)', 'monospace'],
        playfair: ['var(--font-playfair)', 'serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
export default config;
